#ifndef CPPDANFEQTRPT_P_H
#define CPPDANFEQTRPT_P_H

#include <QtCore/qglobal.h>

# ifdef CPPDANFEQTRPT_STATICLIB
#  undef CPPDANFEQTRPT_SHARED
#  define CPPDANFEQTRPT_EXPORT
# else
#  ifdef CPPDANFEQTRPT_BUILD_CPPDANFEQTRPT_LIB
#   define CPPDANFEQTRPT_EXPORT Q_DECL_EXPORT
#  else
#   define CPPDANFEQTRPT_EXPORT Q_DECL_IMPORT
#  endif
# endif

#endif // CPPDANFEQTRPT_P_H
